version: '3'
services:
  nodeapp-test:
    build: 
      context: ../..
      dockerfile: docker/dev/Dockerfile
      args:
        port: ${PORT}
    env_file:
      - ../../environment/dev/dev.env
    environment:
      WAIT_HOSTS: mongo-test:27017
  mongo-test:
    image: mongo:4.0
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=example
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=db-test
      - MONGO_DATA_DIR=/data/db
      - MONGO_TEST_DATA_DIR=/data/test_db
      - MONGO_LOG_FILE=/var/log/mongodb/mongodb.log
    volumes:
      - ".${MONGO_TEST_DATA_DIR}:${MONGO_TEST_DATA_DIR}"
    expose:
      - 27017
    command: "mongod --smallfiles --logpath=${MONGO_LOG_FILE}"