version: '3'
services:
  nodeapp:
    build: 
      context: ../..
      dockerfile: docker/prod/Dockerfile
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ../../environment/prod/production.env  
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    image: mongo:4.0
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=example
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=db
      - MONGO_DATA_DIR=/data/db
      - MONGO_TEST_DATA_DIR=/data/test_db
      - MONGO_LOG_FILE=/var/log/mongodb/mongodb.log
    volumes:
      - ".${MONGO_DATA_DIR}:${MONGO_DATA_DIR}"
    expose:
      - 27017
    command: "mongod --smallfiles --logpath=${MONGO_LOG_FILE}"